// +-------------------------------------------------------------------------------+
// |                                                                               |
// |                         DO NOT MANUALLY MODIFY                                |
// |                                                                               |
// | LAST MODIFIED:  06-29-2020                                                    |
// | This file is auto-generated by scripts/copy_dump.sh via Copy/ProductsCopy.csv |
// |                                                                               |
// +-------------------------------------------------------------------------------+

import Foundation

enum ProductsCopy: String, StringsLoadable {
    case productsListTitle = "products_list_title"
    case productItemUnknownPrice = "product_item_unknown_price"
}
