# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'WaveChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for WaveChallenge
  pod 'Alamofire', '~> 4.5.0'
end
