export const GET_APP_DATA_START = 'APP/GET_APP_DATA_START';
export const GET_APP_DATA_SUCCESS = 'APP/GET_APP_DATA_SUCCESS';
export const GET_APP_DATA_ERROR = 'APP/GET_APP_DATA_ERROR';
export const GET_APP_DATA_PROGRESS = 'APP/GET_APP_DATA_PROGRESS';
export const GET_APP_NETWORK_INFO = 'APP/GET_APP_NETWORK_INFO';
