# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Wave' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wave
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'WaveTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
    pod 'Quick','~>1.0'
  end

  target 'WaveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
